### ISSUE TITLE
Error when attempting to add to conda-forge

### ISSUE THREAD

**Issue by mwilson8** [google/differential-privacy#7]
I'm attempting to add this as a package to conda-forge but am getting an error that I'm unsure of how to fix

I download the source from `https://github.com/google/differential-privacy/archive/master.tar.gz`

And a script that executes `bazel build differential_privacy/...`
Which returns the error 
```ERROR: circular symlinks detected
[start of symlink cycle]
/home/conda/staged-recipes/build_artifacts/google-differential-privacy_1571944966203/_build_env/share/terminfo/N/NCR260VT300WPP
[end of symlink cycle]
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: //differential_privacy/algorithms:bounded-algorithm_test BuildConfigurationValue.Key[bb189304b1c2d885f4d7b75c97be3b24] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp], isDirectlyTransient=false, isTransitivelyTransient=false}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:548)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:365)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

INFO: Elapsed time: 33.934s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (48 packages loaded, 1191 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: //differential_privacy/algorithms:bounded-algorithm_test BuildConfigurationValue.Key[bb189304b1c2d885f4d7b75c97be3b24] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp], isDirectlyTransient=false, isTransitivelyTransient=false}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:548)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:365)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalStateException: //differential_privacy/algorithms:bounded-algorithm_test BuildConfigurationValue.Key[bb189304b1c2d885f4d7b75c97be3b24] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp], isDirectlyTransient=false, isTransitivelyTransient=false}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:548)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:365)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalStateException: //differential_privacy/algorithms:bounded-algorithm_test BuildConfigurationValue.Key[bb189304b1c2d885f4d7b75c97be3b24] false -> ErrorInfo{exception=com.google.devtools.build.lib.skyframe.FileSymlinkCycleException: Symlink cycle, rootCauses={FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp]}, cycles=[], isCatastrophic=false, rootCauseOfException=FILE:[/home/conda/.cache/bazel/_bazel_conda/09cbb6ed10102e8e294ff82d8a8f8c67/external/embedded_jdk]/[lib/terminfo/N/ncr260vt300wpp], isDirectlyTransient=false, isTransitivelyTransient=false}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.assertSaneAnalysisError(SkyframeBuildView.java:548)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.configureTargets(SkyframeBuildView.java:365)
	at com.google.devtools.build.lib.analysis.BuildView.update(BuildView.java:368)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.runAnalysisPhase(AnalysisPhaseRunner.java:212)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:121)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:143)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:253)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:83)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:482)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:750)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$1600(GrpcServerImpl.java:103)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:819)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
FAILED: Build did NOT complete successfully (48 packages loaded, 1191 targets configured)
Traceback (most recent call last):
  File "/home/conda/.ci_support/build_all.py", line 134, in <module>
    build_all(args.recipes_dir, args.arch)
  File "/home/conda/.ci_support/build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File "/home/conda/.ci_support/build_all.py", line 124, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2339, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1487, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 399, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 379, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/conda/staged-recipes/build_artifacts/google-differential-privacy_1571944966203/work/conda_build.sh']' returned non-zero exit status 37.
```

I'm not sure which is causing the error: conda-forge, bazel, or differential-privacy
Please advise if you've encountered this error before when building

**Comment by dasmdasm** [comment]
I haven't seen that error before. It sounds like there might be something about the script you're using to call bazel that introduces a symlink cycle?

**Comment by mwilson8** [comment]
Here is a broken PR for reference: https://github.com/conda-forge/staged-recipes/pull/9975/files

As far as I know, it just spins up a docker container based on a `meta.yaml` file, which shouldn't symlink...? But unfortunately the inner workings of how it's built are unknown to me

**Comment by dasmdasm** [comment]
Not knowing much about conda, I don't see anything obviously wrong there. Are there any other packages in conda-forge that use bazel?

**Comment by mwilson8** [comment]
@jakirkham is there any way I can search recipes for a bazel command in the script?

**Comment by dasmdasm** [comment]
I think solving this is going to require more knowledge of conda-forge than of this library. As is probably obvious, I don't really have time to dig into this at the moment, but I'll leave this open.

**Comment by mwilson8** [comment]
@dasmdasm thanks for what time you could provide. Could Bazel being out of date be a cause of this?

**Comment by dibakch** [comment]
Is this still relevant?  We have updated Bazel to version 4.1.0 recently.

**Comment by dibakch** [comment]
Closing this for now. Please reopen if this is still relevant.

Thanks :)
