### ISSUE TITLE
ctx has no default value error

### ISSUE THREAD

**Issue by mwilson8** [google/differential-privacy#8]
I tried to build differential_privacy locally but received the following error:
```
INFO: Invocation ID: cb40f9d2-f60a-4725-bce4-9ec138569042
ERROR: /private/var/tmp/_bazel_mwilson/1c7c4b22e8073d90fabc5b69394571b5/external/postgres/BUILD.bazel:30:1: in configure_make rule @postgres//:postgres:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_mwilson/1c7c4b22e8073d90fabc5b69394571b5/external/postgres/BUILD.bazel", line 30
		configure_make(name = 'postgres')
	File "/private/var/tmp/_bazel_mwilson/1c7c4b22e8073d90fabc5b69394571b5/external/rules_foreign_cc/tools/build_defs/configure.bzl", line 29, in _configure_make
		cc_external_rule_impl(ctx, attrs)
	File "/private/var/tmp/_bazel_mwilson/1c7c4b22e8073d90fabc5b69394571b5/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 209, in cc_external_rule_impl
		_define_out_cc_info(ctx, attrs, inputs, outputs)
	File "/private/var/tmp/_bazel_mwilson/1c7c4b22e8073d90fabc5b69394571b5/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 636, in _define_out_cc_info
		cc_common.create_compilation_context(headers = depset([outputs.out_in...]), <4 more arguments>)
parameter 'ctx' has no default value, in method call create_compilation_context(depset headers, depset system_includes, depset includes, depset quote_includes, depset defines) of 'cc_common'
ERROR: Analysis of target '//differential_privacy/postgres:anon_func.so' failed; build aborted: Analysis of target '@postgres//:postgres' failed; build aborted
INFO: Elapsed time: 0.200s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

Steps to reproduce:
Download .zip from master branch
In parent dir, `$ bazel build differential_privacy/...`

Other info:
```
$ bazel version
INFO: Invocation ID: 8616bdf6-873e-4dcc-bfb4-033604013b14
Build label: 0.20.0- (@non-git)
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Dec 2 07:51:13 2018 (1543737073)
Build timestamp: 1543737073
Build timestamp as int: 1543737073
```

**Comment by mwilson8** [comment]
I think this was caused by not having the bazelbuild/rules_foreign_cc library available. Closing for now since I've made it past this error
